"""
quant_research.core.events
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Event types for the event-driven trading architecture.

All communication between components flows through typed events:

  MarketData → Signal → Order → Fill

Each event is immutable and timestamped.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class OrderSide(Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"


class OrderStatus(Enum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    PARTIAL = "PARTIAL"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


@dataclass(frozen=True)
class MarketDataEvent:
    """A single bar of market data for one ticker."""
    timestamp: datetime
    ticker: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    adjusted_close: Optional[float] = None

    def __repr__(self) -> str:
        return f"MarketData({self.ticker} @ {self.timestamp.date()} close={self.close:.2f})"


@dataclass(frozen=True)
class SignalEvent:
    """Signal generated by a strategy for a specific ticker."""
    timestamp: datetime
    ticker: str
    signal_value: float       # Target position weight [-1, 1]
    signal_name: str          # e.g., "BTC_TF60"
    confidence: float = 1.0   # Signal confidence [0, 1]

    def __repr__(self) -> str:
        return f"Signal({self.signal_name}: {self.signal_value:+.4f} @ {self.timestamp.date()})"


@dataclass(frozen=True)
class OrderEvent:
    """Order to be submitted to a broker."""
    timestamp: datetime
    ticker: str
    side: OrderSide
    quantity: float           # In units (shares, contracts, coins)
    order_type: OrderType = OrderType.MARKET
    limit_price: Optional[float] = None
    order_id: str = ""

    def __repr__(self) -> str:
        return f"Order({self.side.value} {self.quantity:.4f} {self.ticker} @ {self.timestamp})"


@dataclass(frozen=True)
class FillEvent:
    """Confirmation of an order fill."""
    timestamp: datetime
    ticker: str
    order_id: str
    fill_price: float
    fill_quantity: float      # Positive for buys, negative for sells
    commission: float = 0.0
    slippage: float = 0.0

    @property
    def total_cost(self) -> float:
        return self.commission + self.slippage

    def __repr__(self) -> str:
        return f"Fill({self.ticker} qty={self.fill_quantity:+.4f} @ {self.fill_price:.2f})"


@dataclass(frozen=True)
class RiskEvent:
    """Risk check result event."""
    timestamp: datetime
    check_name: str
    severity: str             # "INFO", "WARNING", "HARD_LIMIT", "KILL"
    message: str
    current_value: float = 0.0
    limit_value: float = 0.0
